var $=jQuery.noConflict();var numberofday=8;$(document).ready(function(){$('#divCart').hide();$('#divEmptyCart').show();setLocalStorageValue();getsubservicedata();var subid=$('#hdnSubId').val();var msid=$('#hdnMainId').val();if(subid!=""&&subid!=null){getinclusiondata(msid,subid);}
AllTimeSlot();$('#btnRemovecoupon').hide();$('#divCouponApplied').hide();$('#btncouponapply').show();$('#divPackage').hide();$('#divMemberPack').hide();$('#divSelectPackage').hide();GetCartItem();});$(window).bind("load",function(){if($('#divServiceSlider').find(".slick-track").length!=0){var sliderLen=parseInt($('#divServiceSlider').find('.slick-track').css("width").replace("px",''));if(sliderLen<=650){$('#divServiceSlider').find('.slick-track').addClass("overridecls");}}
$('#divweakdt11').find('.slick-track').addClass("custSlide");});function localStorage_Data(){if(localStorage.getItem("localStorage_SubServiceList")===undefined||localStorage.getItem("localStorage_SubServiceList")==null){localStorage.setItem("localStorage_SubServiceList",document.getElementById('hdnSubServiceList').value);}else{document.getElementById('hdnSubServiceList').value=localStorage.getItem("localStorage_SubServiceList");}
if(localStorage.getItem("localStorage_InclusionList")===undefined||localStorage.getItem("localStorage_InclusionList")==null){localStorage.setItem("localStorage_InclusionList",document.getElementById('hdnInclusionList').value);}else{document.getElementById('hdnInclusionList').value=localStorage.getItem("localStorage_InclusionList");}
if(localStorage.getItem("localStorage_InclusionBasedDiscountList")===undefined||localStorage.getItem("localStorage_InclusionBasedDiscountList")==null){localStorage.setItem("localStorage_InclusionBasedDiscountList",document.getElementById('hdnInclusionBasedDiscountList').value);}else{document.getElementById('hdnInclusionBasedDiscountList').value=localStorage.getItem("localStorage_InclusionBasedDiscountList");}}
function callshiftdata(valid,sltdt){$("#txt_date").val(sltdt);$("#txt_slttime").val("");$('.SliderBox_Cls').find('li').removeClass('selected');$("#dt"+valid+"").addClass("selected");var firstselecttime="";for(var i=valid,a=0;i<valid+1;i++){if(localStorage.getItem("soltset"+i+"")!=null){var locdt=(localStorage.getItem("soltset"+i+""));var m=JSON.stringify(eval("("+locdt+")"));var response1=JSON.parse(m);var slotsft="";var timsftslt="";var timsftslt1="";for(var j in response1["slotdata"]){if(slotsft==""){slotsft="<li id='li"+j+"'  class='active'><a data-toggle='tab' id='lst"+j+"' href='javascript:void(0);' onclick='showhie("+j+")' >"+response1["slotdata"][j]["dayslotnm"]+"</a></li>";}else{if(response1["slotdata"][j]["dayslotnm"]!="Evening"){slotsft+="<li id='li"+j+"'><a data-toggle='tab' id='lst"+j+"' href='javascript:void(0);' onclick='showhie("+j+")'>"+response1["slotdata"][j]["dayslotnm"]+"</a></li>";}
else{slotsft+="<li id='li"+j+"' style=\"margin-right:0px;\"><a data-toggle='tab' id='lst"+j+"' href='javascript:void(0);' onclick='showhie("+j+")'>"+response1["slotdata"][j]["dayslotnm"]+"</a></li>";}}
timsftslt="";var tmrep=0;for(var k in response1["slotdata"][j].daySlotTime){if(a==0&&tmrep==0){firstselecttime=response1["slotdata"][j].daySlotTime[k].timeslot;}
tmrep=tmrep+1;timsftslt+="<li id='tm"+j+"n"+k+"'><a href='javascript:void(0);' onclick='GetSerTime("+j+","+k+","+tmrep+",\""+response1["slotdata"][j].daySlotTime[k].timeslot+"\" );' >"+response1["slotdata"][j].daySlotTime[k].timeslot+"</a></li>";}
if(timsftslt1==""){timsftslt1="<div id='Morning"+j+"' class='tab-pane active TimeWith_Tabs'><ul id='TimeNo'>"+timsftslt+"</ul></div>"}
else{timsftslt1+="<div id='Morning"+j+"' class='tab-pane TimeWith_Tabs' style=\"display:none;\"><ul id='TimeNo'>"+timsftslt+"</ul></div>"}}
$("#divsltsift").html("<ul class='nav nav-pills'>"+slotsft+" </ul>");$("#divtmesltsft").html(timsftslt1);}
a++;}}
function showhie(id){for(var m=0;m<3;m++){if(m==id){jq("#Morning"+id+"").show();jq("#li"+id+"").addClass("active");}
else{jq("#Morning"+m+"").hide();jq("#li"+m+"").removeClass("active");}}}
function GetSerTime(lp1,timeid,cnt,tmlts){jq("#txt_slttime").val(tmlts);for(var p=0;p<3;p++){for(var m=0;m<8;m++){if(m==timeid){jq("#tm"+lp1+"n"+timeid+"").addClass("selectedtm");}
else{jq("#tm"+p+"n"+m+"").removeClass("selectedtm");}}}
jq("#diverror").html("");}
function getsubservicedata(){var msid=$('#hdnMainId').val();var subserid=$('#hdnSubId').val();$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/GetSubServiceSlider",data:"{'id' :'"+msid+"'}",dataType:"json",async:false,success:function(data){var result=JSON.parse(data.d);var str="",maincat="",subid="";str="<section class=\"regular1 slider1\">";for(let i=0;i<result.length;i++){str+="<div id=\"SliderBox_Cls1\">";str+="<div class=\"AC_SerVice1\">";str+="<a href=\"javascript:void(0);\" id='"+result[i].f_S_C_ID+"' onclick='bindsubservicedata(\""+result[i].f_S_C_ID+"\",this)' class=\"thumbnail123\">";str+="<p>"+result[i].f_Sub_Category_Name+"</p>";str+="</a>";str+="</div>";str+="</div>";if(i==0){maincat=result[i].maincat;if($('#hdnSubId').val()!=""&&$('#hdnSubId').val()!=null){subid=$('#hdnSubId').val();}
else{subid=result[i].f_S_C_ID;$('#hdnSubId').val(subid);}}}
str+="</section>";$("#divServiceSlider").html("");$("#divhed").html("");$("#divServiceSlider").html(str);$("#divhed").html(maincat);document.title=maincat;$("title").text(maincat);$("#serviceheading").html('');$("#serviceheading").html(maincat);$('#'+subid).parent().removeClass('AC_SerVice1');$('#'+subid).parent().addClass('AC_SerVice2');if(subserid==""&&subserid!=null){getinclusiondata(msid,subid);}},error:function(data){}});}
function getinclusiondata(msid,subid){var $=jQuery.noConflict();var sessid=$("#txt_lclstrg").val();var custid=$('#txt_custid').val();$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/GetInclusion",data:"{'smid':'"+msid+"','ssubid': '"+subid+"','sessid':'"+sessid+"','custid':'"+custid+"'}",dataType:"json",async:true,success:function(data){var res='';var result=JSON.parse(data.d);var str="",maincat="",subid="";var servicecharge="";var inclusionid="";for(let i=0;i<result.length;i++){if(i==0){$('#hdnServiceCharge').val('');$('#hdnInclId').val('');servicecharge=result[i].f_Service_Charge;inclusionid=result[i].f_S_ID;$('#hdnServiceCharge').val(servicecharge);$('#hdnInclId').val(inclusionid);}
else{servicecharge=$('#hdnServiceCharge').val()+'_'+result[i].f_Service_Charge;$('#hdnServiceCharge').val(servicecharge);inclusionid=$('#hdnInclId').val()+'_'+result[i].f_S_ID;$('#hdnInclId').val(inclusionid);}
str+="<div class=\"SelectSerVice\">";str+="<div class=\"row\">";str+="<div class=\"col-md-5\">";str+="<p class=\"Dot_10\"><i class=\"fa fa-dot-circle-o fa_custom\"></i>"+result[i].f_Service_Name+"</p>";str+="</div>";str+="<div class=\"col-md-7\">";str+="<div class=\"row\">";str+="<div class=\"col-md-4 col-xs-6 RangePlus\">";str+="<span>";str+="<a href='javascript:void(0);' id='rem"+result[i].f_S_ID+"' onclick='removeitem("+i+","+result[i].f_S_ID+",\""+result[i].f_DiscountType+"\")'><i class=\"fa fa-minus\" aria-hidden=\"true\" id=\"txtadd"+i+"\"></i></a> &nbsp<i class='txtunit"+result[i].f_S_ID+"' id=\"txtunit"+i+"\"> "+result[i].totinclscount+"</i> Units &nbsp<a href='javascript:void(0);' id='add"+result[i].f_S_ID+"'  onclick='additem("+i+","+result[i].f_limit+","+result[i].f_S_ID+",\""+result[i].f_DiscountType+"\")'><i class=\"fa fa-plus\" aria-hidden=\"true\" id=\"txtremove"+i+"\" ></i></a></span>";str+="</div>";res='';if(result[i].discountdetail==""){str+="<div class=\"col-md-2 col-xs-3 \" id=\"divDiscount1"+i+"\">";str+="</div>";str+="<div class=\"col-md-3 col-xs-3 \" id=\"divDiscount2"+i+"\">";str+="<span><i class=\"fa fa-inr\" aria-hidden=\"true\"></i><i id=\"txtServiceAmt"+i+"\">"+result[i].f_Service_Charge+"</i></span>";str+="</div>";str+="<div class=\"col-md-3 col-xs-12\" id=\"divDiscount3"+i+"\">";str+="</div>";}
else{var totamt=0,discountdet='',discountval=0,totqty=parseInt(result[i].totinclscount);str+="<div class=\"col-md-3 col-xs-3\" id=\"divDiscount1"+i+"\">";str+="<span><i class=\"fa fa-inr\" aria-hidden=\"true\" style=\"color:#f34686;\"></i> <del style=\"color:#f34686;\"><i id=\"txtServiceAmt"+i+"\">"+(parseInt(result[i].f_Service_Charge)*parseInt(result[i].totinclscount))+"</i></del></span>";str+="</div>";str+="<div class=\"col-md-3 col-xs-3\" id=\"divDiscount2"+i+"\">";var amt=parseInt(result[i].f_Service_Charge)*parseInt(totqty);if(result[i].discountdetail.split('|')[1]=="Flat"){if(result[i].discountdetail.split('|')[0]=="Without Quantity Based"){discountval=parseInt(result[i].discountdetail.split('|')[2])*parseInt(totqty);discountdet="<i id=\"txtPercent"+i+"\">₹"+(parseInt(result[i].discountdetail.split('|')[2])*parseInt(totqty))+"</i> off"}
else if(result[i].discountdetail.split('|')[0]=="Quantity Based"){if(parseInt(totqty)>parseInt(result[i].discountdetail.split('|')[4])){discountval=Math.round(parseInt(result[i].discountdetail.split('|')[2])+((parseInt(result[i].discountdetail.split('|')[2])/(parseInt(result[i].discountdetail.split('|')[4])))*(parseInt(totqty)-parseInt(result[i].discountdetail.split('|')[4]))));discountdet="<i id=\"txtPercent"+i+"\">₹"+Math.round(parseInt(result[i].discountdetail.split('|')[2])+((parseInt(result[i].discountdetail.split('|')[2])/(parseInt(result[i].discountdetail.split('|')[4])))*(parseInt(totqty)-parseInt(result[i].discountdetail.split('|')[4]))))+"</i> off"}
else{discountval=parseInt(result[i].discountdetail.split('|')[2]);discountdet="<i id=\"txtPercent"+i+"\">₹"+result[i].discountdetail.split('|')[2]+"</i> off"}}
totamt=parseInt(result[i].discountdetail.split('|')[3]);totamt=amt-discountval;}
else if(result[i].discountdetail.split('|')[1]=="Percentage"){discountval=parseInt(result[i].discountdetail.split('|')[2]);totamt=amt-(amt*discountval/100);discountdet="<i id=\"txtPercent"+i+"\">"+discountval+"</i>% off"}
str+="<span><i class=\"fa fa-inr\" aria-hidden=\"true\"></i><i id=\"txtServiceAmtPer"+i+"\">"+Math.round(totamt)+"</i></span>";str+="</div>";str+="<div class=\"col-md-2 col-xs-12\"  id=\"divDiscount3"+i+"\">";str+="<span class=\"OffEr_PerNt\">"+discountdet+"</span>";str+="</div>";}
str+="</div>";str+="</div>";str+="</div>";if(result[i].offerDiscount!=""){var offerdis=result[i].offerDiscount.split('|');str+="<div class=\"row\">";str+="<div class=\"col-md-10 col-xs-10 col-sm-10 \">";str+="</div>";str+="<div class=\"col-md-2 col-xs-2 col-sm-2 Upto_Offer \">";str+="<span class=\"OffEr_PerNt\" id=\"txtOfferDiscount\">upto "+(offerdis[0]=="Flat"?"₹":"")+offerdis[1]+(offerdis[0]=="Percentage"?"%":"")+" off</span>";str+="</div>";str+="</div>";}
str+="<div class=\"row\">";str+="<div class=\"col-md-12\">";str+="<p class=\"StandIns_Tallation\">"+result[i].f_desc+"</p>";str+="</div>";str+="</div>";str+="<div class=\"row\">";str+="<div class=\"col-md-10\">";str+="</div>";str+="<div class=\"col-md-2\">";str+="<button type=\"button\" class=\"btn add-btn\" id=\"btnAddService"+i+"\" onclick='GetServiceDateTime("+i+")'>Add</button>";str+="</div>";str+="</div>";str+="</div>";}
$("#divInclusionList").html("");$("#divInclusionList").html(str);},error:function(err){alert('some issues, plz check');return false;}});}
function bindsubservicedata(subid,th){jQuery('.AC_SerVice2').addClass(' AC_SerVice1')
jQuery('.AC_SerVice2').removeClass('AC_SerVice2 ');jQuery(th).parent().addClass('AC_SerVice2');if(subid!=""&&subid!=null){var msid=$('#hdnMainId').val();$('#hdnSubId').val(subid);getinclusiondata(msid,subid);}
else{return false;}}
function additem(id,limit,inclsid,discountType){var totalunit=$('#txtunit'+id+'').text();var maxlimit=limit;var res=0;var IsPecent=document.getElementById('txtPercent'+id+'');var Pecentage=0;var avalQty=limit;var allseramt=$('#hdnServiceCharge').val();var servicecharge=allseramt.split('_')[id];var totamt=0;var totamtper=0;var packtype=$('#hdnPackageType').val();if(packtype=="1"){var result=getMaxQuantityNormalPackage(inclsid);avalQty=parseInt(result.split('`')[0]);if(avalQty==0||avalQty<=parseInt(totalunit)){alert("Maximum No. of Quantity of "+result.split('`')[1]+" is Used.");return false;}}
if((parseInt(totalunit.trim())<maxlimit)&&avalQty>=(parseInt(totalunit)+1)){res=parseInt(totalunit)+1;$('#txtunit'+id+'').text('');if(res>=10){$('#txtunit'+id+'').text(res);}
else{$('#txtunit'+id+'').text(' '+res);}
SetAllAddedQuantity(inclsid);if(discountType!=""&&discountType!="Without Quantity Based"){getInclsQuantityBasedDiscount(inclsid,res,servicecharge,id,'add',res);}
else{getInclsQuantityBasedDiscount(inclsid,'',servicecharge,id,'add',res);}}}
function removeitem(id,inclsid,discountType){var totalunit=$('#txtunit'+id+'').text();var res=0;var Pecentage=0;var allseramt=$('#hdnServiceCharge').val();var servicecharge=allseramt.split('_')[id];var totamt=0;var totamtper=0;if(parseInt(totalunit)>1){res=parseInt(totalunit)-1;$('#txtunit'+id+'').text('');if(res>=10){$('#txtunit'+id+'').text(res);}
else{$('#txtunit'+id+'').text(' '+res);}
SetAllRemoveQuantity(inclsid);if(discountType!=""&&discountType!="Without Quantity Based"){getInclsQuantityBasedDiscount(inclsid,res,servicecharge,id,'add',res);}
else{getInclsQuantityBasedDiscount(inclsid,'',servicecharge,id,'add',res);}}}
function insertCartItem(id){var $=jQuery.noConflict();var allinclus=$('#hdnInclId').val();var mainid=$('#hdnMainId').val();var subid=$('#hdnSubId').val();var incid=allinclus.split('_')[id];var quantity=$('#txtunit'+id+'').text();var servicetime=$('#txt_slttime').val();if(servicetime==""||servicetime==null){alert("Please select the date and time of service");return false;}
var servicedate=$('#txt_date').val();var custid=$("#txt_custid").val();var sid=$("#txt_lclstrg").val();$("#txt_fnlitm").val("");$("#txt_fnlitm").val("");$("#txt_fnlval").val(incid+"-"+quantity.trim());$("#txt_fnlitm").val(incid);var dataitem=$("#txt_fnlval").val();var specialdis=getdiscountamt(id);$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/InsertData",data:"{date: '"+servicedate+"',timeslt: '"+servicetime+"', itemsid: '"+incid+"',itemsid_quant:'"+quantity.trim()+"' ,custid: '"+custid+"',usrsesion:'"+sid+"',inclusion: '"+incid+"',dataitem:'"+dataitem+"',specialdis:'"+specialdis+"',mainid:'"+mainid+"'}",dataType:"json",success:function(data){if(data!=null){if(data.d!="noslot"){$('#btnAddService'+id+'').attr("disabled",true);$('#btnAddService'+id+'').removeClass("add-btn");$('#btnAddService'+id+'').val("");$('#btnAddService'+id+'').text("Added");$('#btnAddService'+id+'').css("background","#3333339e");$('#btnAddService'+id+'').css("cursor","text");GetCartItem();}
else if(data.d=="noslot"){$('#txt_slttime').val('');alert("Slot Time of "+servicetime+" is already booked! Please Try another time slot.");$('#divmodalservtime').modal({backdrop:'static',keyboard:false});return false;}}
else{alert('Please try again...');}},error:function(data){}});}
function GetCartItem(){var $=jQuery.noConflict();var sessid=$("#txt_lclstrg").val();var custid=$('#txt_custid').val();var packageid=$('#hdnPackageID').val();if(packageid==""||packageid==null||packageid==undefined){packageid="0";}
if($('#divSelectPackage').is(":visible")==true&&custid!=""){packageid=$('#ddl_package option:selected').val();}
var packtype=$('#hdnPackageType').val();var distype=getGreaterDiscount();if(distype!=''&&distype=='spldiscount'){packageid="0";}
$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/gridcartdetal",data:"{sessid: '"+sessid+"',custid: '"+custid+"',packageid:'"+packageid+"'}",dataType:"json",success:function(data){if(data.d!=null&&data.d!=""&&JSON.parse(data.d).length>0){var result=JSON.parse(data.d);var str="",strSummary="",totalamt=0,subid="",cartdisc="",amt=0,overallDiscountAmt=0;for(let i=0;i<result.length;i++){totalamt=parseInt(result[i].overallAmt);amt=parseInt(result[i].f_price)*parseInt(result[i].f_qty);if(i==0){str+="<p>You have Selected "+result.length+" Services</p>";}
str+="<div class=\"row SerVice_Qty\" id=\"divCartHead"+i+"\">";str+="<div class=\"col-md-6 col-xs-4\" style=\"padding:0px\">";str+="<p style=\"color:#f34686;font-weight:bold;\">"+result[i].msc+"</p>";str+="</div>";str+="<div class=\"col-md-3 col-xs-4\"><p style='text-align:center'>Qty</p></div><div class=\"col-md-3 col-xs-4\"><p>Price</p></div>";str+="</div>";str+="<div class=\"row SerVice_Qty1\" id=\"divCartBody"+i+"\">";str+="<div class=\"col-md-6 col-xs-4\" style=\"padding:0px\">";str+="<p id=\""+result[i].f_Service_Item_ID+"\">"+result[i].f_Servce_Item_Name+"</p>";str+="</div>";str+="<div class=\"col-md-3 col-xs-4\">";str+="<span style='text-align:center;display:block;'><a class=\"removeCartQty\" href='javascript:void(0);' onclick='Updateqty("+i+","+result[i].cart_id+",\"remove\","+result[i].f_limit+","+result[i].f_price+","+result[i].f_Service_Item_ID+")'><i class=\"fa fa-minus\" aria-hidden=\"true\" id=\"txtSerAdd"+i+"\"></i></a> &nbsp <i id=\"txtAddServQty"+i+"\">"+result[i].f_qty+"</i> &nbsp<a class=\"addCartQty\"  href='javascript:void(0);' onclick='Updateqty("+i+","+result[i].cart_id+",\"add\","+result[i].f_limit+","+result[i].f_price+","+result[i].f_Service_Item_ID+")'><i class=\"fa fa-plus\" aria-hidden=\"true\" id=\"txtSerRemove"+i+"\"></i></a></span>";str+="</div>";str+="<div class=\"col-md-3 col-xs-4\">";str+="<span>";str+=result[i].tamt!=0?"<i class=\"fa fa-inr\" aria-hidden=\"true\"></i>":"";str+="<i id=\"txtCartAmt"+i+"\">"+result[i].tamt+"</i> <a href='javascript:void(0);' onclick='deletecart("+result[i].cart_id+","+result[i].f_Service_Item_ID+")'><i class=\"fa fa-times\" style=\"color:#f34686;\"></i></a></span>";str+="</div>";str+="</div>";str+="<div class=\"row\" id=\"divCartFooter"+i+"\">";str+="<div class=\"col-md-7 col-xs-5\"></div>";str+="<div class=\"col-md-5 col-xs-7\" style=\"font-size:12px;\"><span>"+result[i].shopdate+", "+result[i].f_ServiceTime+"</span></div>";str+="</div>";if(result[i].f_specialdiscount!="0"){if(cartdisc==""){cartdisc=result[i].cart_id+"_"+result[i].f_specialdiscount;}
else{cartdisc+=","+result[i].cart_id+"_"+result[i].f_specialdiscount;}}
var quantity,str1='';if(result[i].f_discount_type!=""&&result[i].f_discount_type=="Without Quantity Based"){quantity='';}
else{quantity=result[i].f_qty;}
if(result[i].discountdetail!=''){if(result[i].package_nameserive==""){var value=result[i];var discountval=0,disarry="",disprce="0",disper="",amount=0,tot=0,totalamount=0;var totamt=0,amt=0;var inclsid=result[i].f_Service_Item_ID,serviceCharge=result[i].f_price,totqty=result[i].f_qty;var spldisc=$("#hdnspecialdiscount").val();spldisc=spldisc==null||spldisc==undefined?"0":spldisc;var discountdetail=result[i].discountdetail.split('|');if(spldisc=="")
spldisc="0";{{amt=parseInt(serviceCharge)*parseInt(totqty);if(discountdetail[1]=="Flat"){if(discountdetail[0]=="Without Quantity Based"){discountval=parseInt(discountdetail[2])*parseInt(totqty);}
else if(discountdetail[0]=="Quantity Based"){if(parseInt(totqty)>parseInt(discountdetail[4])){discountval=Math.round(parseInt(discountdetail[2])+((parseInt(discountdetail[2])/(parseInt(discountdetail[4])))*(parseInt(totqty)-parseInt(discountdetail[4]))));}
else{discountval=amt-parseInt(discountdetail[3]);}}
totamt=amt-discountval-parseInt(spldisc);}
else if(discountdetail[1]=="Percentage"){discountval=parseInt(discountdetail[2]);totamt=amt-(amt*discountval/100)-parseInt(spldisc);}
overallDiscountAmt+=Math.round(amt-totamt)}
if(i==result.length-1){$("#hdnspecialdiscount").val(parseInt(spldisc)+Math.round(overallDiscountAmt));totamt=parseInt(overallDiscountAmt);str1+="<div class=\"Amount_ToTal\">";str1+="<div class=\"row\">";str1+="<div class=\"col-md-12\"><p>Total :";str1+=totalamt!=0?" <i class=\"fa fa-inr\" aria-hidden=\"true\"></i>":"";str1+=totalamt+"</p><br></div>";str1+="<div class=\"col-md-12\"><p>Discount Amount :";str1+=Math.round(totamt)!=0?" <i class=\"fa fa-inr\" aria-hidden=\"true\"></i>":"";str1+="<i id=\"txtDiscountAmount\">"+Math.round(totamt)+"</i></p><br></div>";str1+="<div class=\"col-md-12\"><p>Final Payable Amount :";str1+=Math.round(totalamt-totamt)!=0?" <i class=\"fa fa-inr\" aria-hidden=\"true\"></i>":"";str1+="<i id=\"txtTotalAmount\">"+Math.round(totalamt-totamt)+"</i></p><br></div>";str1+="<div class=\"col-md-12\"><p>*Inclusive of all the taxes</p></div>";str1+="</div>";str1+="</div>";$("#divCartSummary").html("");$("#divCartSummary").html(str1);$("#hdnOfferDiscAmt").val(Math.round(totamt));}}}}
else{var spldisc=$("#hdnspecialdiscount").val();spldisc=spldisc==null||spldisc==undefined?"0":spldisc;if(spldisc=="")
spldisc="0";str1+="<div class=\"Amount_ToTal\">";str1+="<div class=\"row\">";str1+="<div class=\"col-md-12\"><p>Total :";str1+=totalamt!=0?" <i class=\"fa fa-inr\" aria-hidden=\"true\"></i>":""
str1+=totalamt+"</p><br></div>";str1+="<div class=\"col-md-12\"><p>Discount Amount :";str1+=Math.round(parseInt(spldisc))!=0?" <i class=\"fa fa-inr\" aria-hidden=\"true\"></i>":"";str1+="<i id=\"txtDiscountAmount\">"+Math.round(parseInt(spldisc))+"</i></p><br></div>";str1+="<div class=\"col-md-12\"><p>Final Payable Amount :";str1+=Math.round(parseInt(totalamt)-parseInt(spldisc))!=0?" <i class=\"fa fa-inr\" aria-hidden=\"true\"></i>":"";str1+="<i id=\"txtTotalAmount\">"+Math.round(parseInt(totalamt)-parseInt(spldisc))+"</i></p><br></div>";str1+="<div class=\"col-md-12\"><p>*Inclusive of all the taxes</p></div>";str1+="</div>";str1+="</div>";$("#divCartSummary").html("");$("#divCartSummary").html(str1);$("#hdnOfferDiscAmt").val(Math.round(parseInt(spldisc)));}
if(i==result.length-1){var disvl=result[i].DiscountPrice;var specldisct=result[i].f_specialdiscount;var disarry=disvl.split('-');var disctamt=disarry[0]!=null||disarry[0]!=""?disarry[0]:"0"
var disprce=parseInt(disctamt)+parseInt(specldisct);var disper=disarry[1];if(cartdisc==""){$("#hdnSpclDiscCartid").val(cartdisc);}else{$("#hdnSpclDiscCartid").val("0");}
if(packageid!=""&&packageid!=null&&packageid!=undefined&&packageid!="0"){getPackageDiscountCartDetail(i);}
else{getMemberPackageDetail();}}}
$("#hdnspecialdiscount").val('0');$("#hdncouponcodeid").val("");$("#divAddedService").html("");$("#divAddedService").html(str);$("#btnRemovecoupon").hide();$("#btncouponapply").show();$("#txtcouponcode").val("");$('#divCouponApplied').hide();$('#divCart').show();$('#divEmptyCart').hide();if(packageid==""||packageid==null||packageid==undefined||packageid=="0"){$('#divPackage').hide();$("#txtPackageDetail").html("");}
if($("#hdn_PackageCount").val()!="0"&&parseInt($("#hdn_PackageCount").val())>=2){$('#divSelectPackage').show();$('#divPackage').hide();$('#divMemberPack').hide();}
if(parseInt($("#hdnOfferDiscAmt").val())>=1000){$('#divMemberPack').hide();$("#txtPackageDetail").html("");$("#txtPackageDetail").html("<b><span style=\"color: #f34686\">Congratulations… you got the best possible discount.</span></b>");$('#divPackage').show();}}
else{$("#divAddedService").html("");$("#divCartSummary").html("");$('#divPackage').hide();$('#divCart').hide();$('#divEmptyCart').show();}
getCartDetail(sessid,custid);getHeaderCartCnt();},error:function(data){}});}
function Updateqty(id,cid,type,limit,amount,inclsid){var txtqty=$('#txtAddServQty'+id+'').text();var txtid="";var maxlimit=limit;var spldiscount=0;var avalQty=limit;if(type=="add"){if(parseInt(txtqty)==maxlimit){return false;}
else{txtid=parseInt(txtqty)+1
var packtype=$('#hdnPackageType').val();if(packtype=="1"){var result=getMaxQuantityNormalPackage(inclsid);avalQty=parseInt(result.split('`')[0]);if(avalQty==0){alert("Maximum No. of Quantity of "+result.split('`')[1]+" is Used.");return false;}}}}
if(type=="remove"){if(parseInt(txtqty)==1){return false;}
else{txtid=parseInt(txtqty)-1}}
jq.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/updatecartdetal",data:"{ cid: '"+cid+"',txtid: '"+txtid+"',inclsid: '"+inclsid+"',amount:"+amount+"}",dataType:"json",async:false,success:function(data){if(data=="notsucc"){}
if(data=="succ"){}
$("#divCouponApplied").hide();$('#divPackage').hide();$("#txtPackageDetail").html("");var msid=$('#hdnMainId').val();var subid=$('#hdnSubId').val();if(subid!=""&&subid!=null){getinclusiondata(msid,subid);}
GetCartItem();},error:function(result){}});}
function deletecart(id,inclsid){if(id!=""){if(confirm('Are sure want to delete this item to cart?')){var path="Handler/daletecrt.ashx?cid="+id;$.ajax({url:path,type:"POST",async:false,success:function(data){if(data=="succ"){$("#btnRemovecoupon").hide();$("#btncouponapply").show();$("#divCouponApplied").hide();$("#txtcouponcode").val("");$('#divMemberPack').hide();$('[id^=btnAddService]').attr("disabled",false);$('[id^=btnAddService]').addClass("add-btn");$('[id^=btnAddService]').val("");$('[id^=btnAddService]').text("Add");$('[id^=btnAddService]').css("background","#f34686");var addedqty=parseInt(getAddedCartQty(inclsid).split(',')[0]);$(".txtunit"+inclsid).text("");$(".txtunit"+inclsid).text(addedqty);var msid=$('#hdnMainId').val();var subid=$('#hdnSubId').val();getinclusiondata(msid,subid);GetCartItem();}},error:function(data){}})}
else{return false;}}}
function setLocalStorageValue(){var valuid="";var historyTmp1;var historyTmp_get1;if(localStorage.getItem("lastsessionID1")!=null){historyTmp_get1=localStorage.getItem("lastsessionID1");$("#txt_lclstrg").val(historyTmp_get1);}
valuid=document.getElementById("usidaft").value;var newval="";if(valuid!=""){newval=valuid;}
else{newval=historyTmp_get1;}
var path="../Handler/getcartcount.ashx?sesstionid="+newval;$.ajax({url:path,type:"GET",crossDomain:true,success:function(data){localStorage.setItem("CartItemCount",data);},error:function(data){}})}
function AllTimeSlot(){var slotdate="",slotweak="",slotdtstr="";var fulldtloc="";var dm=0;var NoOfDayes="8";jq.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/AllTimeSlots",data:"{'NoOfDayes':'"+NoOfDayes+"'}",dataType:"json",success:function(response){var m=JSON.stringify(eval(JSON.parse(response.d)));var resdatetimenew1=JSON.parse(response.d);var cdtchk=resdatetimenew1.CurrentDate;if((resdatetimenew1.StatusCode)=="1"){for(var i in resdatetimenew1.All){slotdate=resdatetimenew1.All[i].DateVal;slotweak=resdatetimenew1.All[i].WeekDay;if(i==0){if(cdtchk==slotdate){slotweak="Today";dm=1;}else{slotweak="Tomorrow";dm=2;}}
else if(i==1&&dm==1){slotweak="Tomorrow";}
localStorage.removeItem("soltset"+i+"");var onldt=slotdate.split('/');slotdtstr+="<div id='SliderBox_Cls1'><ul class='SliderBox_Cls'><li id='dt"+i+"' ><a href='javascript:void(0);' onclick='callshiftdata("+i+",\""+slotdate+"\")'>"+slotweak+"<br /><label> "+onldt[0]+"</label></a></li></ul></div>";var alllocdata="";for(var j in resdatetimenew1.All[i].AvlbleSlot){var daylocdata="";for(var k in resdatetimenew1.All[i].AvlbleSlot[j].daySlots){var timelocdata="";if(daylocdata==""){daylocdata="{'dayslotnm':'"+resdatetimenew1.All[i].AvlbleSlot[j].daySlots[k].daySlotsName+"'";}
else{daylocdata=daylocdata+","+"{'dayslotnm':'"+resdatetimenew1.All[i].AvlbleSlot[j].daySlots[k].daySlotsName+"'";}
for(var l in resdatetimenew1.All[i].AvlbleSlot[j].daySlots[k].daySlotTime){if(timelocdata==""){timelocdata="{'timeslot':'"+resdatetimenew1.All[i].AvlbleSlot[j].daySlots[k].daySlotTime[l].timeVal+"'}";}
else{timelocdata=timelocdata+","+"{'timeslot':'"+resdatetimenew1.All[i].AvlbleSlot[j].daySlots[k].daySlotTime[l].timeVal+"'}";}}
daylocdata=daylocdata+","+"'daySlotTime':["+timelocdata+"],'sltdate': '"+slotdate+"'}";}}
fulldtloc="";fulldtloc=daylocdata
jq("#dt0").addClass("selected");localStorage.setItem("soltset"+i+"","{'slotdata':["+fulldtloc+"]}");if(i==0){callshiftdata(0,slotdate);}}}
else{jq("#divtmesltsft").html("No Record Found");jq("#divtmesltsft").css("color","red");jq("#divtmesltsft").css("font-weight","bold");jq("#divtmesltsft").css("font-size","22px");jq("#divtmesltsft").css("padding-top","10px");jq("#divtmesltsft").css("padding-bottom","16px");jq("#btn_submitvl").hide();}}});}
function SetCookies(){var $=jQuery.noConflict();$.ajax({url:'servicelist_time.aspx/locals',contentType:'application/json;charset=utf-8',type:'post',dataType:'json',data:"{vala: '"+$('#txt_lclstrg').val()+"'}",success:function(_data){},error:function(_err){}});}
function getMemberPackageDetail(){var sessid=$("#txt_lclstrg").val();var custid=$('#txt_custid').val();$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/getMemberPackageDetail",data:"{'sessionid':'"+sessid+"','custid': '"+custid+"'}",dataType:"json",async:false,success:function(data){var pack=JSON.parse(data.d);if(pack.length>0){$('#divMemberPack').show();$('#divPackageDetail').html("");$('#divPackageDetail').html("<p>Get Extra Discount of <span style=\"color: #f34686\">Rs."+Math.round(pack[0].Amount)+".</span> Buy <a href='../package/"+pack[0].PackageName.replace(/ /g,"-")+"')'><span style=\"color: #f34686\">"+pack[0].PackageName+"</span></a></p>");}},error:function(result){}});}
function getPackageDiscountCartDetail(){var sessid=$("#txt_lclstrg").val();var custid=$('#txt_custid').val();var packtype=$('#hdnPackageType').val();$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/getPackageDiscountCartDetail",data:"{'custId': '"+custid+"'}",dataType:"json",async:false,success:function(data){var result=JSON.parse(data.d);if(result.length>0){var disvl="0",disarry="",disprce="0",disper="",amount=0,tot=0,totalamount=0;for(let i=0;i<result.length;i++){disvl=result[i].DiscountPrice;disarry=disvl.split('-');disprce=disarry[0]!=null||disarry[0]!=""?disarry[0]:"0";disper=disarry[1];amount=parseInt(result[i].f_price)*parseInt(result[i].f_qty);totalamount+=(parseInt(amount));if(i==result.length-1&&packtype!='1'){$("#hdnSpclDiscCartid").val("");$("#hdncouponcodeid").val("");$("#txtTotalAmount").text("");$("#txtTotalAmount").text(Math.round(totalamount.toFixed(2)-parseInt(disprce).toFixed(2)));$("#hdnpayableamount").val(Math.round(totalamount.toFixed(2)-parseInt(disprce).toFixed(2)));$("#txtDiscountAmount").text("");$("#txtDiscountAmount").text(disprce);}}
$("#txtPackageDetail").html("");var packageType=$('#hdnPackageType').val();if(parseInt(packageType)==1){$("#txtPackageDetail").html("Applied <b> <span style=\"color: #f34686\">"+$("#hdnPackageName").val()+"</span></b>");}else if(parseInt(packageType)==2){$("#txtPackageDetail").html("<b><span style=\"color: #f34686\">Congratulations … Membership discount applied succesfully.</span></b>");}
$('#divPackage').show();$('#divMemberPack').hide();}},error:function(result){}});}
function getInclsQuantityBasedDiscount(inclsid,quantity,serviceCharge,id,action,totqty){var str='';$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/getInclsQuantityBasedDiscount",data:"{'inclsid':'"+inclsid+"','quantity': '"+quantity+"'}",dataType:"json",async:true,success:function(data){var value=JSON.parse(data.d);var i=0;if(data.d!=null&&data.d!=""&&value.length>0&&value[i].Row==undefined){var str1="",str2="",str3="";if(value.length>0){if(value[i].f_Minimum_Amount<=serviceCharge){if(action=="new"){str+="<div class=\"col-md-2 col-xs-3\" id=\"divDiscount1"+id+"\">";str+="<span><i class=\"fa fa-inr\" aria-hidden=\"true\" style=\"color:#f34686;\"></i> <del style=\"color:#f34686;\"><i id=\"txtServiceAmt"+id+"\">"+serviceCharge+"</i></del></span>";str+="</div>";str+="<div class=\"col-md-3 col-xs-3\" id=\"divDiscount2"+id+"\">";var amt=parseInt(serviceCharge);var totamt=0;var discountval=0;var discountdet='';if(value[i].f_DiscountType=="Flat"){discountval=parseInt(value[i].f_Flat);totamt=amt-discountval;discountdet="<i id=\"txtPercent"+id+"\">₹"+value[i].f_Flat+"</i> off"}
else if(value[i].f_DiscountType=="Percentage"){discountval=parseInt(value[i].f_Percentage);totamt=amt-(amt*discountval/100);discountdet="<i id=\"txtPercent"+id+"\">"+value[i].f_Percentage+"</i>% off"}
str+="<span><i class=\"fa fa-inr\" aria-hidden=\"true\"></i><i id=\"txtServiceAmtPer"+id+"\">"+Math.round(totamt)+"</i></span>";str+="</div>";str+="<div class=\"col-md-3 col-xs-12\"  id=\"divDiscount3"+id+"\">";str+="<span class=\"OffEr_PerNt\">"+discountdet+"</span>";str+="</div>";}
else if(action=="add"||action=="remove"){var amt=parseInt(serviceCharge)*parseInt(totqty);var totamt=0;var discountval=0;var discountdet='';if(value[i].f_DiscountType=="Flat"){if(value[i].f_Type=="Without Quantity Based"){discountval=parseInt(value[i].f_Flat)*parseInt(totqty);discountdet="<i id=\"txtPercent"+id+"\">₹"+(parseInt(value[i].f_Flat)*parseInt(totqty))+"</i> off"}
else if(value[i].f_Type=="Quantity Based"){if(parseInt(totqty)>parseInt(value[i].f_Quantity)){discountval=Math.round(parseInt(value[i].f_Flat)+((parseInt(value[i].f_Flat)/(parseInt(value[i].f_Quantity)))*(parseInt(totqty)-parseInt(value[i].f_Quantity))));discountdet="<i id=\"txtPercent"+id+"\">₹"+Math.round(parseInt(value[i].f_Flat)+((parseInt(value[i].f_Flat)/(parseInt(value[i].f_Quantity)))*(parseInt(totqty)-parseInt(value[i].f_Quantity))))+"</i> off";}
else{discountval=parseInt(value[i].f_Flat);discountdet="<i id=\"txtPercent"+id+"\">₹"+value[i].f_Flat+"</i> off";}}
totamt=amt-discountval;}
else if(value[i].f_DiscountType=="Percentage"){discountval=parseInt(value[i].f_Percentage);totamt=amt-(amt*discountval/100);discountdet="<i id=\"txtPercent"+id+"\">"+value[i].f_Percentage+"</i>% off"}
str1+="<span><i class=\"fa fa-inr\" aria-hidden=\"true\" style=\"color:#f34686;\"></i> <del style=\"color:#f34686;\"><i id=\"txtServiceAmt"+id+"\">"+amt+"</i></del></span>";str2+="<span><i class=\"fa fa-inr\" aria-hidden=\"true\"></i><i id=\"txtServiceAmtPer"+id+"\">"+Math.round(totamt)+"</i></span>";str3+="<span class=\"OffEr_PerNt\">"+discountdet+"</span>";$("#divDiscount1"+id+"").html("");$("#divDiscount1"+id+"").html(str1);$("#divDiscount2"+id+"").html("");$("#divDiscount2"+id+"").html(str2);$("#divDiscount3"+id+"").html("");$("#divDiscount3"+id+"").html(str3);}}
if(value[i].offerDiscount!=""){var offerdis=value[i].offerDiscount.split('|');$('#txtOfferDiscount').text('');$('#txtOfferDiscount').text("Upto "+(offerdis[0]=="Flat"?"₹":"")+offerdis[1]+(offerdis[0]=="Percentage"?"%":"")+" off");}}}
else{var str1="",str2="",str3="";{str2+="<span><i class=\"fa fa-inr\" aria-hidden=\"true\"></i><i id=\"txtServiceAmt"+id+"\">"+parseInt(serviceCharge)*parseInt(totqty)+"</i></span>";$("#divDiscount1"+id+"").html("");$("#divDiscount2"+id+"").html("");$("#divDiscount2"+id+"").html(str2);$("#divDiscount3"+id+"").html("");}
if(value[i].Row!=undefined){if(value[i].OfferDisc!=""){var offerdis=value[i].OfferDisc.split('|');$('#txtOfferDiscount').text('');$('#txtOfferDiscount').text("upto "+(offerdis[0]=="Flat"?"₹":"")+offerdis[1]+(offerdis[0]=="Percentage"?"%":"")+" off");}}}},error:function(result){}});return str;}
function getdiscountamt(id){var totalunit=$('#txtunit'+id+'').text();var allseramt=$('#hdnServiceCharge').val();var servicecharge=allseramt.split('_')[id];var nodiscountamt=parseInt(servicecharge)*parseInt(totalunit)
var specialdis=0;var withdiscountamt=$('#txtServiceAmtPer'+id+'').text();var isdiscount=document.getElementById('txtServiceAmtPer'+id+'');if(isdiscount!=null){specialdis=nodiscountamt-parseInt(withdiscountamt);}
return specialdis;}
function onclickbtnprocced(){var $=jQuery.noConflict();var spcid=$("#hdnSpclDiscCartid").val();var cupid=$('#hdncouponcodeid').val();var msg=CheckMainServiceMinValue();if(msg=="false"){return false;}
$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/getProceedBook",data:"{'spcid': '"+spcid+"','cupid': '"+cupid+"'}",dataType:"json",success:function(data){if(data.d!=""&&data.d!=null&&data.d!=undefined){if(data.d=="open"){$('.divcheckotp').hide();$('.divotp').show();$('#errorlog').html('');$('#txt_umobile').val('');$('#txt_otp').val('');$('#divmodallogin').modal({backdrop:'static',keyboard:false});}
else if(data.d=="nocart"){alert('Cart is empty.Add item first.');}
else{window.location=data.d;}}},error:function(result){}});}
function setCartQuantityBasedDiscount(inclsid,quantity,serviceCharge,totqty,totalamt,packtype){var str='';$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/getInclsQuantityBasedDiscount",data:"{'inclsid':'"+inclsid+"','quantity': '"+quantity+"'}",dataType:"json",async:false,success:function(data){var len=JSON.parse(data.d).length;if(data.d!=null&&data.d!=""&&len!=0){if(packtype==""){var value=JSON.parse(data.d);var i=0;var str1="",str2="",str3="";var discountval=0,disarry="",disprce="0",disper="",amount=0,tot=0,totalamount=0;var totamt=0,amt=0;var spldisc=$("#hdnspecialdiscount").val();spldisc=spldisc==null||spldisc==undefined?"0":spldisc;if(spldisc=="")
spldisc="0";if(value.length>0){for(let i=0;i<value.length;i++){amt=parseInt(serviceCharge)*parseInt(totqty);if(value[i].f_DiscountType=="Flat"){if(value[i].f_Type=="Without Quantity Based"){discountval=parseInt(value[i].f_Flat)*parseInt(totqty);}
else if(value[i].f_Type=="Quantity Based"){if(parseInt(totqty)>parseInt(value[i].f_Quantity)){discountval=parseInt(value[i].f_Flat)*(parseInt(totqty)-parseInt(value[i].f_Quantity)+1);}
else{discountval=parseInt(value[i].f_Flat);}}
totamt=totalamt-discountval-parseInt(spldisc);}
else if(value[i].f_DiscountType=="Percentage"){discountval=parseInt(value[i].f_Percentage);totamt=totalamt-(amt*discountval/100)-parseInt(spldisc);}
$("#hdnspecialdiscount").val(parseInt(spldisc)+Math.round(totalamt-totamt));}
str+="<div class=\"Amount_ToTal\">";str+="<div class=\"row\">";str+="<div class=\"col-md-12\"><p>Total :";str+=totalamt!=0?" <i class=\"fa fa-inr\" aria-hidden=\"true\"></i>":"";str+=totalamt+"</p><br></div>";str+="<div class=\"col-md-12\"><p>Discount Amount :";str+=Math.round(totalamt-totamt)!=0?" <i class=\"fa fa-inr\" aria-hidden=\"true\"></i>":"";str+="<i id=\"txtDiscountAmount\">"+Math.round(totalamt-totamt)+"</i></p><br></div>";str+="<div class=\"col-md-12\"><p>Final Payable Amount :";str+=Math.round(totamt)!=0?" <i class=\"fa fa-inr\" aria-hidden=\"true\"></i>":"";str+="<i id=\"txtTotalAmount\">"+Math.round(totamt)+"</i></p><br></div>";str+="<div class=\"col-md-12\"><p>*Inclusive of all the taxes</p></div>";str+="</div>";str+="</div>";$("#divCartSummary").html("");$("#divCartSummary").html(str);$("#hdnOfferDiscAmt").val(Math.round(totalamt-totamt));}}}
else{var spldisc=$("#hdnspecialdiscount").val();spldisc=spldisc==null||spldisc==undefined?"0":spldisc;if(spldisc=="")
spldisc="0";str+="<div class=\"Amount_ToTal\">";str+="<div class=\"row\">";str+="<div class=\"col-md-12\"><p>Total :";str+=totalamt!=0?" <i class=\"fa fa-inr\" aria-hidden=\"true\"></i>":""
str+=totalamt+"</p><br></div>";str+="<div class=\"col-md-12\"><p>Discount Amount :";str+=Math.round(parseInt(spldisc))!=0?" <i class=\"fa fa-inr\" aria-hidden=\"true\"></i>":"";str+="<i id=\"txtDiscountAmount\">"+Math.round(parseInt(spldisc))+"</i></p><br></div>";str+="<div class=\"col-md-12\"><p>Final Payable Amount :";str+=Math.round(parseInt(totalamt)-parseInt(spldisc))!=0?" <i class=\"fa fa-inr\" aria-hidden=\"true\"></i>":"";str+="<i id=\"txtTotalAmount\">"+Math.round(parseInt(totalamt)-parseInt(spldisc))+"</i></p><br></div>";str+="<div class=\"col-md-12\"><p>*Inclusive of all the taxes</p></div>";str+="</div>";str+="</div>";$("#divCartSummary").html("");$("#divCartSummary").html(str);$("#hdnOfferDiscAmt").val(Math.round(parseInt(spldisc)));}},error:function(result){}});return str;}
function CheckMainServiceMinValue(){var sessid=$("#txt_lclstrg").val();var custid=$('#txt_custid').val();var msg="true";$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/GetMainServiceMinValue",data:"{ sessid: '"+sessid+"',custid: '"+custid+"'}",dataType:"json",async:false,success:function(data){var res=data.d.split("-");if(res[0]=="notsucc"){alert("Minimum Cart Amount of "+res[2]+" is above or equal to ₹ "+res[1]);msg="false";}},error:function(result){}});return msg;}
$(function(){$('#ddl_package').change(function(){GetCartItem();});setInterval(function(){$('#divDateError').hide();},3000);$('.SliderBox_Cls').find('li').click(function(){$(this).find('a').trigger('onclick');})})
function getHeaderCartCnt(){var valuid="";var historyTmp1;var historyTmp_get1;if(localStorage.getItem("lastsessionID1")!=null){historyTmp_get1=localStorage.getItem("lastsessionID1");$('#Header1_txt_lclstrg1').val(historyTmp_get1);}
valuid=$('#usidaft').val();var newval="";if(valuid!=""){newval=valuid;}
else{newval=historyTmp_get1;}
var path='../default.aspx/getcartcount';var obj={'sesstionid':newval};$.ajax({url:path,type:'post',contentType:'application/json; charset=utf-8',dataType:'JSON',data:JSON.stringify(obj),success:function(data){data=data.d;jq("#crt").text(data);},error:function(data){}});}
function SetServiceDateTime(){var $=jQuery.noConflict();var isExist='';var sessid=$("#txt_lclstrg").val();var custid=$('#txt_custid').val();var obj={sessonid:sessid,usridnew:custid};$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/isPackageExist",dataType:"json",data:JSON.stringify(obj),async:false,success:function(data){if(data.d!='start'){if(parseInt(data.d)>0){isExist='1';}}
if(isExist=='1'){if(confirm('You already have a package added to your cart. Adding the services will delete the previously added package in your cart. Do you wish to continue')){$.ajax({url:"ServiceBooking.aspx/emptycart",contentType:"application/json; charset=utf-8",type:"POST",data:JSON.stringify(obj),async:false,success:function(data){isExist='';},error:function(data){}});}else{isExist='0';}}}});var id=$('#hdnSelectDateTimeID').val();var servicetime=$('#txt_slttime').val();if(servicetime==""||servicetime==null){$('#divDateError').show();return false;}
if(id!=null&&id!=""){$('#divmodalservtime').modal('hide');insertCartItem(id);}}
function GetServiceDateTime(id){var $=jQuery.noConflict();var servicetime=$('#txt_slttime').val();if(servicetime==""||servicetime==null){if(id!=null)
$('#hdnSelectDateTimeID').val(id);$('#divweakdt11').find('.slick-track').removeClass("custSlide");if(window.matchMedia("only screen and (max-width: 760px)").matches){$('#divweakdt11').find('.slick-track').css('width','4947px');$('#divweakdt11').find('.slick-track').css('transform',' translate3d(-291px, 0px, 0px)');$('#divweakdt11').find('.slick-slide').css('width','291px');}
else{$('#divweakdt11').find('.slick-track').css('width','2919px');$('#divweakdt11').find('.slick-track').css('transform',' translate3d(-695px, 0px, 0px)');$('#divweakdt11').find('.slick-slide').css('width','139px');}
$('#divmodalservtime').modal({backdrop:'static',keyboard:false});}
else{insertCartItem(id);}}
function SetAllAddedQuantity(inclsid){if($('#divAddedService').html()!=""){$('.SerVice_Qty1').each(function(){if($(this).find('p').attr('id')==inclsid){$(this).find('.addCartQty').first().click();return false;}})}}
function SetAllRemoveQuantity(inclsid){if($('#divAddedService').html()!=""){$('.SerVice_Qty1').each(function(){if($(this).find('p').attr('id')==inclsid){$(this).find('.removeCartQty').first().click()
return false;}})}}
function getAddedCartQty(inclsid){var sessid=$("#txt_lclstrg").val();var custid=$('#txt_custid').val();var addedqty='1';{$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/getAddedCartQty",data:"{'sessionid':'"+sessid+"','custid': '"+custid+"','inclsid': '"+inclsid+"'}",dataType:"json",async:false,success:function(data){var result=JSON.parse(data.d);if(result.length>0){addedqty=result[0].f_qty+','+result[0].f_DiscountType;}},error:function(result){}});}
return addedqty;}
function updateofferprice(inclsid){var count=0;$('.SelectSerVice').each(function(){if($(this).html().indexOf(inclsid)>-1){id=count;return false;}
count++;})
var totalunit=$('#txtunit'+id+'').text();var discountType=getAddedCartQty(inclsid).split(',')[1];var res=0;var allseramt=$('#hdnServiceCharge').val();var servicecharge=allseramt.split('_')[id];res=parseInt(totalunit);if(discountType!=""&&discountType!="Without Quantity Based"&&discountType!=undefined){getInclsQuantityBasedDiscount(inclsid,res,servicecharge,id,'add',res);}
else{getInclsQuantityBasedDiscount(inclsid,'',servicecharge,id,'add',res);}}
function getGreaterDiscount(){var custid=$('#txt_custid').val();var memberdiscount=0;$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/getGreaterDiscount",data:"{custid: '"+custid+"'}",dataType:"json",async:false,success:function(data){var result=JSON.parse(data.d);if(result.length>0){memberdiscount=result[0].DiscountType;}},error:function(result){}});return memberdiscount;}
function getMaxQuantityNormalPackage(inclsid){var custid=$('#txt_custid').val();var availableqty=0;$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/getMaxQuantityNormalPackage",data:"{custid: '"+custid+"',inclsid: '"+inclsid+"'}",dataType:"json",async:false,success:function(data){var result=JSON.parse(data.d);if(result.length>0){availableqty=result[0].availableqty;availableqty=availableqty=='0'?'20':availableqty;}},error:function(result){}});return availableqty;}
function getUpdateQtySpecialDiscount(inclsid,quantity,amount){var spldiscount=0;var totqty=quantity;var servicecharge=amount;$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/getInclsQuantityBasedDiscount",data:"{'inclsid':'"+inclsid+"','quantity': '"+quantity+"'}",dataType:"json",async:true,success:function(data){var value=JSON.parse(data.d);if(data.d!=null&&data.d!=""&&value.length>0){var i=0;if(value.length>0){if(value[i].f_Minimum_Amount<=amount){var amt=parseInt(amount)*parseInt(totqty);if(value[i].f_DiscountType=="Flat"){if(value[i].f_Type=="Without Quantity Based"){spldiscount=parseInt(value[i].f_Flat)*parseInt(totqty);}
else if(value[i].f_Type=="Quantity Based"){if(parseInt(totqty)>parseInt(value[i].f_Quantity)){spldiscount=parseInt(value[i].f_Flat)*(parseInt(totqty)-parseInt(value[i].f_Quantity)+1);}
else{spldiscount=parseInt(value[i].f_Flat);}}}
else if(value[i].f_DiscountType=="Percentage"){spldiscount=parseInt(value[i].f_Percentage);}}}}},error:function(result){}});return spldiscount;}