function currentLocation(){var startPos;var nudge=document.getElementById("nudge");var showNudgeBanner=function(){nudge.style.display="block";};var hideNudgeBanner=function(){nudge.style.display="none";};var nudgeTimeoutId=setTimeout(showNudgeBanner,5000);var geoOptions={enableHighAccuracy:true}
var geoSuccess=function(position){hideNudgeBanner();clearTimeout(nudgeTimeoutId);startPos=position;var latlng=new google.maps.LatLng(startPos.coords.latitude,startPos.coords.longitude);var geocoder=geocoder=new google.maps.Geocoder();geocoder.geocode({'latLng':latlng},function(results,status){if(status==google.maps.GeocoderStatus.OK){if(results[1]){alert("Location: "+results[1].formatted_address);}}});};var geoError=function(error){switch(error.code){case error.TIMEOUT:showNudgeBanner();break;}};navigator.geolocation.getCurrentPosition(geoSuccess,geoError);};function initMap(){var input=document.getElementById('txt_servicelocation');var options={componentRestrictions:{country:'In'}};var autocomplete=new google.maps.places.Autocomplete(input,options);autocomplete.addListener('place_changed',function(){var place=autocomplete.getPlace();if(!place.geometry){document.getElementById('hdn_lat').value="";document.getElementById('hdn_long').value="";window.alert("No details available for input: '"+place.name+"'");return;}
var address='';if(place.address_components){address=[(place.address_components[0]&&place.address_components[0].short_name||''),(place.address_components[1]&&place.address_components[1].short_name||''),(place.address_components[2]&&place.address_components[2].short_name||''),].join(' ');}
var pincode="",city,state,country;for(var i=0;i<place.address_components.length;i++){for(var j=0;j<place.address_components[i].types.length;j++){if(place.address_components[i].types[j]=="postal_code"){pincode=place.address_components[i].long_name;}
if(place.address_components[i].types[j]=="locality"){city=place.address_components[i].long_name;}
if(place.address_components[i].types[j]=="administrative_area_level_1"){state=place.address_components[i].long_name;}
if(place.address_components[i].types[j]=="country"){country=place.address_components[i].long_name;}}}
var latValue=place.geometry.location.lat();var longValue=place.geometry.location.lng();matchcity(city,address,pincode,city,state,country,latValue,longValue);});}
function geolocate(){if(navigator.geolocation){navigator.geolocation.getCurrentPosition(function(position){var geolocation={lat:position.coords.latitude,lng:position.coords.longitude};});}}
function assignvaluetocontrol(address,pincode,city,state,country,latValue,longValue){var $=jQuery.noConflict();var divadd=document.getElementById('errorregister');divadd.innerHTML="";$("#txt_servicelocation").removeClass('red');if(address==""){document.getElementById('txt_servicelocation').value="";$("#txt_servicelocation").addClass('red');divadd.innerHTML='Enter Valid Area';}
document.getElementById('hdn_serviceaddress').value=address;if(pincode!=""){var j=checkPinCodeRunTime(pincode);if(j=="0"){pincode="";}}
document.getElementById('hdn_servicepincode').value=pincode;document.getElementById('txt_pincode').value=pincode;if(pincode==""){$("#txt_pincode").addClass('red');}
else{$("#txt_pincode").removeClass('red');}
document.getElementById('txtcity').value=city;document.getElementById('txt_state').value=state;document.getElementById('hdn_lat').value=latValue;document.getElementById('hdn_long').value=longValue;}
function matchcity(cityname,address,pincode,city,state,country,latValue,lonValue){var status="";var $=jQuery.noConflict();$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/matchcity",data:"{'cityname': '"+cityname+"'}",dataType:"json",success:function(data){if(data.d=="exist"){assignvaluetocontrol(address,pincode,city,state,country,latValue,lonValue);}
else{assignvaluetocontrol("","","","","","","");alert("Currently lifeasy is not providing services on selected location");}},error:function(result){alert("Something is wrong");}});}
function checkPinCode(){var jq=jQuery.noConflict();var pincode=jq("#txt_pincode").val();var state=jq("#txt_state").val();var txt_servicelocation=jq("#txt_servicelocation").val();if(txt_servicelocation!=""){if(pincode!=""){jq.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/checkPincode",data:"{'pincode': '"+pincode+"'}",dataType:"json",async:false,success:function(data){if(data.d=="Not"){jq("#txt_pincode").addClass('red');alert("Currently lifeasy is not providing services on this pincode");document.getElementById('txt_pincode').value="";}
else{if(data.d.toUpperCase()!=state.toUpperCase()){jq("#txt_pincode").addClass('red');alert("This pincode not available in "+state+"");document.getElementById('txt_pincode').value="";}}},error:function(result){alert("Something is wrong");}});}}
else{alert("Kindly fill the area field first");}}
function checkPinCodeRunTime(txt_pincode){var jq=jQuery.noConflict();var pincode=txt_pincode;if(pincode!=""){jq.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/checkPincode",data:"{'pincode': '"+pincode+"'}",dataType:"json",async:false,success:function(data){if(data.d=="Not"){return "0";}
else{return "1";}},error:function(result){alert("Something is wrong");}});}}
$(function(){var $=jQuery.noConflict();$("#txt_servicelocation").keypress(function(e){document.getElementById('hdn_lat').value="";if((e.which&&e.which==13)||(e.keyCode&&e.keyCode==13)){return false;}else{return true;}});});function locateMe(){var ua=navigator.userAgent.toLowerCase();if(!((ua.indexOf('safari')==91)||(ua.indexOf('safari')==103))){var startPos;var nudge=document.getElementById("nudge");var showNudgeBanner=function(){nudge.style.display="block";};var hideNudgeBanner=function(){nudge.style.display="none";};var nudgeTimeoutId=setTimeout(showNudgeBanner,5000);var geoOptions={enableHighAccuracy:true}
var geoSuccess=function(position){hideNudgeBanner();clearTimeout(nudgeTimeoutId);startPos=position;var latlng=new google.maps.LatLng(startPos.coords.latitude,startPos.coords.longitude);var geocoder=geocoder=new google.maps.Geocoder();geocoder.geocode({'latLng':latlng},function(results,status){if(status==google.maps.GeocoderStatus.OK){if(results[1]){for(var i=0;i<results[0].address_components.length;i++){for(var b=0;b<results[0].address_components[i].types.length;b++){if(results[0].address_components[i].types[b]=="locality"){city=results[0].address_components[i];}
if(results[0].address_components[i].types[b]=="postal_code"){pincode=results[0].address_components[i];}
if(results[0].address_components[i].types[b]=="administrative_area_level_1"){state=results[0].address_components[i];}
if(results[0].address_components[i].types[b]=="country"){country=results[0].address_components[i];}}}
var latValue2=startPos.coords.latitude;var longValue2=startPos.coords.longitude;;matchcityLocateMe(city.long_name,results[0].formatted_address,pincode.long_name,city.long_name,state.long_name,country.long_name,latValue2,longValue2);}}});};var geoError=function(error){switch(error.code){case error.TIMEOUT:showNudgeBanner();break;}};navigator.geolocation.getCurrentPosition(geoSuccess,geoError);}
else{alert("You have blocked auto detect location for Lifeasy. Please enter your location");}};function matchcityLocateMe(cityname,address,pincode,city,state,country,latValue,lonValue){var status="";var $=jQuery.noConflict();$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/matchcity",data:"{'cityname': '"+cityname+"'}",dataType:"json",success:function(data){if(data.d=="exist"){assignvaluetocontrolLocateMe(address,pincode,city,state,country,latValue,lonValue);}
else{assignvaluetocontrolLocateMe("","","","","","","");alert("Currently lifeasy is not providing services on selected location");}},error:function(result){alert("Something is wrong");}});}
function assignvaluetocontrolLocateMe(address,pincode,city,state,country,latValue,longValue){var $=jQuery.noConflict();var divadd=document.getElementById('errorregister');divadd.innerHTML="";$("#txt_servicelocation").removeClass('red');if(address==""){document.getElementById('txt_servicelocation').value="";$("#txt_servicelocation").addClass('red');divadd.innerHTML='Enter Valid Area';}
document.getElementById('hdn_serviceaddress').value=address;if(pincode!=""){var j=checkPinCodeRunTime(pincode);if(j=="0"){pincode="";}}
document.getElementById('hdn_servicepincode').value=pincode;document.getElementById('txt_pincode').value=pincode;if(pincode==""){$("#txt_pincode").addClass('red');}
else{$("#txt_pincode").removeClass('red');}
var area=address.split(",");document.getElementById('txt_address').value=area[0];document.getElementById('txt_servicelocation').value=address;document.getElementById('txtcity').value=city;document.getElementById('txt_state').value=state;document.getElementById('hdn_lat').value=latValue;document.getElementById('hdn_long').value=longValue;}