var $=jQuery.noConflict();function calltimeout(){setTimeout(function(){$('#errorlog').empty();},7000);}
function Logvalidation1(){var txtuser=$("#txt_umobile").val();var num0to5=[0,1,2,3,4,5];var msg='';$('#errorlog').empty();if(txtuser==''){var placeholder=$('#txt_umobile').attr('placeholder');msg=placeholder;}else if(txtuser.length<=10){if(!isNaN(txtuser)){if(num0to5.indexOf(parseInt(txtuser.charAt(0)))>=0||txtuser.length!=10){msg='1';}}else{msg='1';}}
if(msg!=''){msg=(msg==1?'Enter Correct Mobile No':msg);$('#errorlog').append(msg);calltimeout();return false;}else{sendOTP();return true;}}
function isNumber(){var regex=new RegExp("^[0-9]+$");var key=String.fromCharCode(!event.charCode?event.which:event.charCode);if(!regex.test(key)){event.preventDefault();return false;}}
function LogvalidationOtp(){var txtmobile=$("#txt_umobile").val();var txtotp=$("#txt_otp").val();var msg="";var num0to5=[0,1,2,3,4,5];if(txtmobile==""){$("#txt_umobile").attr("placeholder","Enter Mobile No");msg="1";}
if(txtotp==""){var placeholder=$("#txt_otp").attr("placeholder");$("#txt_otp").attr("placeholder",placeholder);msg="1";}
if(msg!=""){calltimeout();return false;}
return true;}
function sendOTP(){var txtmobile=$("#txt_umobile").val();var sessid=$("#txt_lclstrg").val();if(txtmobile.length==10){$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/checkMobile",data:"{Mobile: '"+txtmobile+"', sess: '"+sessid+"'}",dataType:"json",async:false,success:function(data){$('#hdn_unverifiedCust').val(txtmobile);var path="../Handler/resendotp.ashx?mobile="+txtmobile+"&is_reg="+data.d;$.ajax({url:path,type:"POST",success:function(data){$('#txt_otp').val('');$("#errorlog").empty();$("#errorlog").css("color","green");$("#errorlog").append("OTP sent successfully");$(".divotp").hide();$(".divcheckotp").show();calltimeout()},error:function(data){}});},error:function(result){alert("Something is wrong");}});}
else{$("#errorlog").text("Enter correct mobile no.");have=false;}}
function OpenSignUpPop(mob){var $=jQuery.noConflict();$('#divmodallogin').modal("hide");$("#divmodallogin").find("input[type=text]").val('');$("#divmodalsigngup").find("input[type=text]").val('');$('#txt_mobile').val(mob);$('#txt_mobile').attr('readonly',true);$('#txt_mobile').css('cursor','not-allowed');$('#divmodalsigngup').modal({backdrop:'static',keyboard:false});}
$(function(){$("#ddl_area").change(function(){if($("#ddl_area").val()=="0"){$("#ddl_area").addClass('red');return false;}
else{$("#errorregister").empty();$("#ddl_area").removeClass('red');$("#txt_pincode").removeClass('red');}})
$("#txt_pincode,#txt_mobile").keypress(function(){var regex=new RegExp("^[0-9]+$");var key=String.fromCharCode(!event.charCode?event.which:event.charCode);if(!regex.test(key)){event.preventDefault();return false;}})
$("#txt_pincode").blur(function(){if($("#txt_pincode").val()!=""){$("#ddl_area").empty();var pincode=$("#txt_pincode").val();$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/BindArea",data:"{'pincode': '"+pincode+"'}",dataType:"json",success:function(data){$("#ddl_area").append($("<option></option>").val("0").html("Please select the area/location"));if(data.d.length>0){$.each(data.d,function(key,value){$("#ddl_area").append($("<option></option>").val(value.areaname).html(value.areaname));$("#txtcity").val(value.cityname);$("#txt_state").val(value.statename);});}
else{$("#txtcity").val("");$("#txt_state").val("");}},error:function(result){alert("Error");}});}})})
function checkMailStatus(valsnd){var $=jQuery.noConflict();var txtuser=$("#txt_name").val();var txtemail=$("#txt_email").val();var txtmobile=$("#txt_mobile").val();var txtpass=$("#txt_passreg").val();var txtconfpass=$("#txt_confpass").val();var txtpin=$("#txt_pincode").val();var txtaddress=$("#txt_address").val();var txtcity=$("#txt_city").val();var txtstate=$("#txt_state").val();var txtaltmob=$("#txt_altmob").val();var txt_servicelocation=$("#txt_servicelocation").val();var hdn_latval=$("#hdn_lat").val();var divadd=document.getElementById('errorservicelocation');$('#errorregister').text('');var msg="";if(document.getElementById('termsconditions').checked==false){$("#termsconditions").addClass('red');msg="Check Terms & Conditions";}
else{$("#termsconditions").removeClass('red');}
if(txtpin==""){$("#txt_pincode").addClass('red');$("#txt_pincode").attr("placeholder","Enter PinCode");msg="Enter PinCode";}
else{$("#txt_pincode").removeClass('red');}
if(txtpin!=""){var numbers2=/^[0-9]+$/;if(txtpin.match(numbers2)){$("#txt_pincode").removeClass('red');}
else{$("#txt_pincode").addClass('red');msg="Pin Code Should Be Number";}}
if(txt_servicelocation==""){$("#txt_servicelocation").addClass('red');$("#txt_servicelocation").attr("placeholder","Enter Service Area");}
else{if(hdn_latval==""){}
else{$("#txt_servicelocation").removeClass('red');}}
if(txtaddress==""){$("#txt_address").addClass('red');$("#txt_address").attr("placeholder","Flat / House No");msg="Enter Flat / House No";}
else{$("#txt_address").removeClass('red');}
if(txtpass!=""&&txtconfpass!=""){if(txtpass==txtconfpass){$("#txt_passreg").removeClass('red');$("#txt_confpass").removeClass('red');}
else{$("#txt_passreg").addClass('red');$("#txt_confpass").addClass('red');msg="Password Not Match";}}
else{$("#txt_confpass").addClass('red');$("#txt_confpass").attr("placeholder","Enter Confirm Password");msg="Enter Confirm Password";}
if(txtpass==""){$("#txt_passreg").addClass('red');$("#txt_passreg").attr("placeholder","Enter Password");msg="Enter Password";}
else{if(txtpass.length<6){$("#txt_passreg").addClass('red');msg="password should be minimun 6 character";}else{$("#txt_passreg").removeClass('red');}}
if(txtaltmob!=""){var numbers3=/^[0-9]+$/;if(txtaltmob.match(numbers3)){$("#txt_altmob").removeClass('red');}
else{$("#txt_altmob").addClass('red');$("#errorregister").append("Number Only");msg="Number Only";}}
if(txtmobile!=""){var numbers1=/^[0-9]+$/;if(txtmobile.match(numbers1)){$("#txt_mobile").removeClass('red');}
else{$("#txt_mobile").addClass('red');msg="Number Only";}}
if(txtmobile!=""){var moblnth=$("#txt_mobile").val().length;if(txtmobile.charAt(0)!=7&&txtmobile.charAt(0)!=8&&txtmobile.charAt(0)!=9||moblnth!=10){$("#txt_mobile").addClass('red');msg="Please fill correct mobile no";}else if(IsMobileExist(txtmobile)==true){$("#txt_mobile").addClass('red');msg="Mobile No. Already Exists";$('#errorregister').text('Mobile No. Already Exists');return false;}
else{$("#txt_mobile").removeClass('red');}}else{$("#txt_mobile").addClass('red');$("#txt_mobile").attr("placeholder","Enter Mobile No.");msg="Enter Mobile No.";}
var reg=/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;if(txtemail!=""){if(reg.test(txtemail)==false&&txtemail!=''){$("#txt_email").addClass('red');msg="EmailID should be in proper format";}else if(IsEmailExist(txtemail)==true){$("#txt_email").addClass('red');msg='EmailID Already Exists';$('#errorregister').text('EmailID Already Exists');return false;}
else{$("#txt_usname").removeClass('red');}}
if(txtuser!=''){var txt=$('#txt_name').val();var re=/^[ A-Za-z_,./+-]*$/
if(re.test(txt)){$("#txt_name").removeClass('red');}
else{$("#txt_name").addClass('red');msg="Special characters not allowed in Full Name";}}
else{$("#txt_name").addClass('red');$("#txt_name").attr("placeholder","Enter Full Name");msg="Enter Full Name";}
if(msg!=""){$("#errorregister").append(msg);return false;}
else{if(valsnd=="1"){getregister();}
return true;}}
function IsEmailExist(email){var $=jQuery.noConflict();var ishave=false;$.ajax({url:'ServiceBooking.aspx/IsEmailExist',type:'POST',contentType:'application/json;charset=utf-8',dataType:'json',data:"{customeremail: '"+email+"',flag: '12'}",async:false,success:function(data){ishave=false;if(data.d=='Exist'){ishave=true;}}});return ishave;}
function IsMobileExist(mob){var $=jQuery.noConflict();var ishave=false;$.ajax({url:'ServiceBooking.aspx/IsMobileExist',type:'POST',contentType:'application/json;charset=utf-8',dataType:'json',data:"{customermob: '"+mob+"',flag: '12'}",async:false,success:function(data){ishave=false;if(data.d=='Exist'){ishave=true;}}});return ishave;}
function getregister(){var $=jQuery.noConflict();$("#lodr").removeClass("lodr1");$("#lodr").addClass("lodr");$("#lodr").css("display","block");$("#nonldr").css("display","none");var txtname=$("#txt_name").val();var txtemail=$("#txt_email").val();var txtmobile=$("#txt_mobile").val();$("#hdnmo").val(txtmobile);var txtpass=$("#txt_passreg").val();var txtconfpass=$("#txt_confpass").val();var txtpin=$("#txt_pincode").val();var txtaddress=$("#txt_servicelocation").val();var txtaddress1=$("#txt_address").val();var lat=$("#hdn_lat").val();var long1=$("#hdn_long").val();var txtaltmobile=$("#txt_altmob").val();var fbid=$("#hdnfbid").val();var gid=$("#hdngoogleid").val();var gender="";if($("#rdmale").is(":checked")==true){gender="Male";}
else{gender="Female"}
var path="../Handler/userregistration.ashx?txtname="+txtname+"&mailid="+txtemail+"&mobile="+txtmobile+"&passwrd="+encodeURIComponent(txtpass)+"&txtpin="+txtpin+"&address="+encodeURIComponent(txtaddress)+"&sessionval="+encodeURIComponent($("#txt_lclstrg").val())+"&altmob="+txtaltmobile+"&area="+encodeURIComponent(txtaddress1)+"&gender="+gender+"&fbid="+fbid+"&gid="+gid+"&lat="+lat+"&long="+long1+"&f_pincode_service="+txtpin;$.ajax({url:path,type:"POST",success:function(data){$("#lodr").css("display","none");$("#nonldr").css("display","block");$("#lodr").removeClass("lodr");$("#lodr").addClass("lodr1");$("#lodr").css("display","table-cell!important");var spcld=$("#hdnSpclDiscCartid").val();var cupid=$("#hdncouponcodeid").val();spcld=(spcld==null||spcld==undefined||spcld=="")?"":encryptdata(spcld);cupid=(cupid==null||cupid==undefined||cupid=="")?"":encryptdata(cupid);if(data=="Exist"){$("#errorregister").append("User already registered");$("#txt_name").val('');$("#txt_email").val('');$("#txt_mobile").val('');$("#txt_passreg").val('');$("#txt_confpass").val('');$("#txt_pincode").val('');$("#txt_address1").val('');$("#txt_address").val('');$("#txt_city").val('Select City');$("#txt_state").val('');$('#txt_servicelocation').val('');$('#txtcity').val('');}else{var dataArr=data.split('-');if(dataArr[0]=="succ"){var mo="";var mo1="";mo=$("#hdnmo").val();if(mo!=""&&mo!=null&&mo!=undefined)
mo1=mo.replace(/0/gi,"j").replace(/1/gi,"i").replace(/2/gi,"t").replace(/3/gi,"e").replace(/4/gi,"n").replace(/5/gi,"d").replace(/6/gi,"r").replace(/7/gi,"a").replace(/8/gi,"k").replace(/9/gi,"s");var qs=getQueryStrings();var myParam=qs["shpval"];window.location="../checkout.aspx?cup="+cupid+"&spc="+spcld+"";}}},error:function(data){}})}
function getQueryStrings(){var assoc={};var decode=function(s){return decodeURIComponent(s.replace(/\+/g," "));};var queryString=location.search.substring(1);var keyValues=queryString.split('&');for(var i in keyValues){var key=keyValues[i].split('=');if(key.length>1){assoc[decode(key[0])]=decode(key[1]);}}
return assoc;}
function checkMailStatus1(valsnd){$("#errorregister").empty();var txtuser=$("#txt_name").val();var txtemail=$("#txt_email").val();var txtmobile=$("#txt_mobile").val();var txtpass=$("#txt_passreg").val();var txtconfpass=$("#txt_confpass").val();var txtpin=$("#txt_pincode").val();var txtaddress=$("#txt_address").val();var txtcity=$("#txt_city").val();var txtstate=$("#txt_state").val();var txtaltmob=$("#txt_altmob").val();var msg="";$("#txt_name").on("input",function(){if(txtuser==""){$("#txt_name").addClass('red');$("#txt_name").attr("placeholder","Enter Full Name");$("#errorregister").empty();$("#errorregister").append("Enter Full Name");msg="1";}
else{$("#errorregister").empty();$("#txt_name").removeClass('red');}
if(txtuser!=''){var txt=$('#txt_name').val();var re=/^[ A-Za-z_,./+-]*$/
if(re.test(txt)){$("#txt_name").removeClass('red');$("#errorregister").empty();}
else{$("#txt_name").addClass('red');$("#errorregister").empty();$("#errorregister").append("Special characters not allowed in Full Name");msg=1;}}});$("#txt_email").on("input",function(){var reg=/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;if(txtemail!=""){if(reg.test(txtemail)==false&&txtemail!=''){$("#txt_email").addClass('red');$("#errorregister").empty();$("#errorregister").append("EmailID should be in proper format");msg="1";}
else{$("#errorregister").empty();$("#txt_email").removeClass('red');}}});$("#txt_mobile").on("input",function(){if(txtmobile==""){$("#txt_mobile").addClass('red');$("#txt_mobile").attr("placeholder","Enter Mobile No.");$("#errorregister").empty();$("#errorregister").append("Enter Mobile No.");msg="1";}
else{$("#errorregister").empty();$("#txt_mobile").removeClass('red');}
if(txtmobile!=""){var numbers1=/^[0-9]+$/;if(txtmobile.match(numbers1)){$("#txt_mobile").removeClass('red');$("#errorregister").empty();}
else{$("#txt_mobile").addClass('red');$("#errorregister").empty();$("#errorregister").append("Number Only");msg="1";}}
if(txtmobile!=""){var moblnth=$("#txt_mobile").val().length;if(txtmobile.charAt(0)!=7&&txtmobile.charAt(0)!=8&&txtmobile.charAt(0)!=9||moblnth!=10){$("#txt_mobile").addClass('red');$("#errorregister").empty();$("#errorregister").append("Please fill correct mobile no");msg="1";}
else{$("#txt_mobile").removeClass('red');$("#errorregister").empty();}}});$("#txt_altmob").on("input",function(){if(txtaltmob!=""){var numbers3=/^[0-9]+$/;if(txtaltmob.match(numbers3)){$("#txt_altmob").removeClass('red');$("#errorregister").empty();}
else{$("#txt_altmob").addClass('red');$("#errorregister").empty();$("#errorregister").append("Number Only");msg="1";}}});$("#txt_passreg").on("input",function(){if(txtpass==""){$("#txt_passreg").addClass('red');$("#txt_passreg").attr("placeholder","Enter Password");$("#errorregister").empty();$("#errorregister").append("Enter Password");msg="1";}
else{$("#errorregister").empty();$("#txt_passreg").removeClass('red');}});$("#txt_confpass").on("input",function(){if(txtconfpass==""){$("#txt_confpass").addClass('red');$("#txt_confpass").attr("placeholder","Enter Confirm Password");$("#errorregister").empty();$("#errorregister").append("Enter Confirm Password");msg="1";}
else{$("#errorregister").empty();$("#txt_confpass").removeClass('red');}});$("#txt_confpass").on("input",function(){if(txtpass!=""&&txtconfpass!=""){if(txtpass==txtconfpass){$("#errorregister").empty();$("#txt_passreg").removeClass('red');$("#txt_confpass").removeClass('red');}
else{$("#txt_passreg").addClass('red');$("#txt_confpass").addClass('red');$("#errorregister").empty();$("#errorregister").append("Password Not Match");msg="1";}}});$("#txt_pincode").on("input",function(){if(txtpin==""){$("#txt_pincode").addClass('red');$("#txt_pincode").attr("placeholder","Enter PinCode");$("#errorregister").empty();$("#errorregister").append("Enter PinCode");msg="1";}
else{$("#errorregister").empty();$("#txt_pincode").removeClass('red');}
if(txtpin!=""){var numbers2=/^[0-9]+$/;if(txtpin.match(numbers2)){$("#txt_pincode").removeClass('red');$("#errorregister").empty();}
else{$("#txt_pincode").addClass('red');$("#errorregister").empty();$("#errorregister").append("Pin Code Should Be Number");msg="1";}}});$("#txt_address").on("input",function(){if(txtaddress==""){$("#txt_address").addClass('red');$("#txt_address").attr("placeholder","Enter Full Address");$("#errorregister").empty();$("#errorregister").append("Enter Complete Address");msg="1";}
else{$("#errorregister").empty();$("#txt_address").removeClass('red');}});if($("#ddl_area").val()=="0"){$("#ddl_area").addClass('red');$("#errorregister").empty();$("#errorregister").text("Please select the area/location");msg="1";}
else{$("#errorregister").empty();$("#ddl_area").removeClass('red');}
if(msg!=""){return false;}
else{if(valsnd=="1"){getregister();}
return true;}}
function clickButton(e,buttonid){var evt=e?e:window.event;var bt=document.getElementById(buttonid);if(bt){if(evt.keyCode==13){bt.click();return false;}}}
function checkTempCustomerOtp(){var $=jQuery.noConflict();var mobile=$("#txt_umobile").val();var otp=$("#txt_otp").val();var sessid=$("#txt_lclstrg").val();var have=true;$.ajax({type:"POST",contentType:"application/json;charset=utf-8",url:"ServiceBooking.aspx/tempuserOtpCheck",data:"{Mobile: '"+mobile+"',otp: '"+otp+"', ss: '"+sessid+"'}",dataType:"json",async:false,success:function(data){var val=data.d.split('_');if(val[0]=='verified-tempuser'){$('#txt_otp').val('');have=false;OpenSignUpPop(val[1]);}else if(data.d!=''&&data.d!='verified'){$('#txt_otp').val('');$('#errorlog').text(data.d);have=false;}},error:function(_err){have=false;}});return have;}
function checkotp(){var $=jQuery.noConflict();var txtuser=$("#txt_umobile").val().trim();var num0to5=[0,1,2,3,4,5];var msg='';$('#errorlog').empty();if(document.getElementById('txt_otp').value.trim()==''){msg='Enter Otp';}else if(document.getElementById('txt_otp').value.trim().length!=6){msg='Enter correct Otp';}
if(txtuser==''){msg='Enter Mobile Number';}else if(txtuser.length<=10){if(!isNaN(txtuser)){if(num0to5.indexOf(parseInt(txtuser.charAt(0)))>=0||txtuser.length!=10){msg='1';}}else{msg='1';}}
if(msg!=''){msg=(msg=='1'?'Enter Correct Mobile No':msg);$('#errorlog').append(msg);return false;}else{return checkTempCustomerOtp();}}
function encryptdata(encval){var encretval="";$.ajax({type:"POST",contentType:"application/json; charset=utf-8",url:"ServiceBooking.aspx/encryptdata",data:"{'strQueryString':'"+encval+"'}",dataType:"json",async:false,success:function(data){encretval=data.d;},error:function(result){}});return encretval;}